src/layout/components/AppMain/index.vue
=> fix(AppMain): :bug: 修复混合模式开启固定Header时的样式问题

src/layout/components/Sidebar/components/SidebarMenuItemTitle.vue
=> refactor(SidebarMenuItemTitle): :recycle: 去除冗余代码

.env.development, vite.config.ts
利用 .env.d.ts 中声明的参数 VITE_APP_API_URL 来做 env 配置
=> build(vite.config.ts): :package: 代理接口地址通过env配置文件修改

.husky/commit-msg, .husky/pre-commit
[https://github.com/typicode/husky/releases/tag/v9.0.1](https://github.com/typicode/husky/releases/tag/v9.0.1)
=> build(husky): :package: husky9.x版本适配

src/settings.ts
=> refactor(settings.ts): :recycle: 默认固定Header

src/views/dashboard/index.vue
Expected to return a value in computed function.eslint([vue/return-in-computed-property](https://eslint.vuejs.org/rules/return-in-computed-property.html))
=> fix(dashboard): :bug: 修复eslint报错

mock/user.mock.ts, src/components/PageContent/index.vue, src/hooks/usePage.ts, src/views/demo/curd/config/content.ts, src/views/demo/curd/index.vue
为方便体验CURD全部功能，麻烦大大增加几个权限点标识：查询（sys:user:query）、导出（sys:user:export）、导入（sys:user:import）、重置密码（sys:user:reset_pwd）
=> refactor: :recycle: 抽离CURD的使用部分代码为Hooks实现

src/api/auth/index.ts, src/api/dept/index.ts, src/api/dict/index.ts, src/api/file/index.ts, src/api/menu/index.ts, src/api/role/index.ts, src/api/user/index.ts, src/typings/global.d.ts
axios 响应拦截处理中，当 code 为 00000 时，代码中返回的是 response.data，其实它的 TS 类型已经不是 AxiosResponse 了，但是使用时还是在按 AxiosResponse 获取，从而导致 then 回调获取不到正确的代码提示
PS：演示地址的用户 perms 字段返回为空数组了...
=> refactor: :recycle: 优化axios响应数据TS类型提示

src/components/IconSelect/index.vue
支持ep图标检索
支持选择图标后关闭
增加选择箭头动画
优化弹窗触发位置
=> refactor: :recycle: 重构图标选择组件

src/components/TableSelect/index.vue, src/typings/components.d.ts
=> feat: :sparkles: 增加列表选择组件

src/layout/components/Settings/index.vue
关于[页面抖动问题](https://github.com/youlaitech/vue3-element-admin/issues/29) ，目前无法通过简单的弹窗属性设置解决。只要是页面内容过长出现滚动条，再打开 dialog 或者 drawer 之类的都会有这个问题，参考了 [vue-pure-admin](https://github.com/pure-admin/vue-pure-admin)，感觉要从整体页面样式布局上解决这个问题
=> fix: :bug: 修复系统设置面板滚动条问题

src/components/PageContent/index.vue, src/views/demo/curd/config/content2.ts
switch配合modifyAction接口可以修改列表行某个字段的值
=> feat(PageContent): :sparkles: 支持switch属性修改

src/directive/permission/index.ts, src/plugins/permission.ts
抽离后不仅可以在组件中使用指令方式判断权限，还可以使用函数方式判断
同时还支持单个字符串权限点的判断（非数组形式）
=> refactor: :recycle: 抽离权限判断代码

src/components/PageContent/index.vue
列表switch操作的权限点名称为 xxx:modify，如 sys:user:modify
=> feat(PageContent): :sparkles: 增加switch权限控制

src/components/PageContent/index.vue, src/views/demo/curd/config/content2.ts
同switch，input也可以配合modifyAction接口来修改列表行某个字段的值，比如排序数值
=> feat(PageContent): :sparkles: 支持input属性修改

src/components/PageModal/Form.vue, src/components/PageModal/index.vue, src/components/PageModal/types.ts
比如，可以在 watch 函数中实现监听该值的变化，进而控制某些表单项的显示和隐藏
=> watch函数增加配置项参数返回

src/components/PageModal/index.vue
修复表单抽离为组件后，表单项自定义插槽失效问题
优化表单项 computed 实现方式
另外：dict/gender/options 接口返回数据中的value值为字符串，而用户gender数据返回的是数字，从而存在 select 无法正确选中问题
=> fix(PageModal): :bug: 修复表单插槽失效问题

src/views/demo/curd/config/add.ts, src/views/demo/curd/config/edit.ts, src/views/demo/curd/index.vue
- 性别使用dictionary组件渲染
- 修改密码操作接口对接
=> refactor: :recycle: 修改CURD示例

src/components/PageContent/index.vue, src/hooks/usePage.ts, src/views/demo/curd/config/content.ts
- pagination：配置分页参数(pagination组件属性)
- request：默认的分页相关的请求参数
- parseData：数据格式解析的回调函数
=> feat(PageContent): :sparkles: 增加pagination、request、parseData配置参数

src/App.vue
=> fix: :bug: 修复水印层级问题

src/layout/index.vue
修复混合布局固定header时tagsview存在左侧偏移量问题
=> fix: :bug: 修复混合布局样式问题

src/components/PageModal/index.vue
resetFields会触发新的空Validate，需在nextTick清除
=> fix: :bug: 修复关闭弹窗时没有clearValidate问题

package.json, src/components/PageContent/index.vue, src/typings/shims-vue.d.ts
表格支持前端导出，去除xlsx库(很久没维护了)，改用exceljs
=> feat(PageContent): :sparkles: 支持前端导出

src/components/PageSearch/index.vue
=> feat(PageSearch): :sparkles: 支持标签输入框

src/components/PageContent/index.vue, src/components/PageModal/index.vue
只需配置 exportsAction 返回数据即可前端全量导出
=> feat(PageContent): :sparkles: 前端导出支持全量数据

src/components/PageContent/index.vue
默认支持跨页选中，如果不想跨页选中可以配置 selection 所在行的 reserve-selection 为 false
=> feat(PageContent): :sparkles: 支持选中数据导出

src/components/PageContent/index.vue, src/views/demo/curd/config/content.ts
=> refactor: :recycle: 修改CURD导出示例

src/components/PageContent/index.vue, src/hooks/usePage.ts, src/views/demo/curd/config/content.ts
=> feat(PageContent): :sparkles: 支持默认工具栏的导入

src/components/CURD/PageContent.vue, src/components/CURD/types.ts, src/views/demo/curd/config/content.ts, src/views/demo/curd/index.vue
=> feat(PageContent): :sparkles: 支持后端文件导入

src/components/CURD/PageContent.vue, src/components/CURD/types.ts, src/views/demo/curd/config/content.ts
importsTemplate 改为 importTemplate
=> refactor(PageContent): ♻️ 导入模板参数改名

src/components/CURD/PageForm.vue, src/components/CURD/PageModal.vue
比如搜狗PC浏览器，Object.havOwn 会报错，使用 Object.prototype.hasOwnProperty 替代
=> fix: 修复 Object.hasOwn 浏览器兼容性问题

src/components/CopyButton/index.vue, src/types/components.d.ts, src/views/demo/curd/config/content.ts, src/views/demo/curd/index.vue, src/views/demo/icons.vue
复制功能在后台管理平台里也算是高频需求，为了方便使用，封装了 CopyButton 组件。
另外，useClipboard 在PC的搜狗等某些浏览器上会有兼容性问题，为了解决该问题对 handleClipboard 做了兼容。
=> feat: 增加复制组件，解决 useClipboard 兼容性问题

src/views/error-page/401.vue, src/views/error-page/404.vue
=> fix: :bug: 修复错误页样式问题

src/layout/components/Settings/index.vue, src/layout/components/Sidebar/components/SidebarMenu.vue, src/layout/index.vue
=> fix: :bug: 修复移动端切换顶部布局模式时的遮罩问题

.prettierrc.cjs
=> style: :lipstick: 解决Prettier格式化操作后结束标签>跑到下一行的问题

src/components/CURD/PageForm.vue, src/components/CURD/PageModal.vue, src/components/CURD/types.ts
col 配置参数同 Layout 布局组件的 [Col Attributes](https://element-plus.org/zh-CN/component/layout.html#col-attributes)
=> feat(PageModal): :sparkles: 表单项增加col配置参数

index.html, package.json, src/components/TextScroll/index.vue, src/views/demo/drag.vue, src/views/demo/text-scroll.vue
1.优化首屏加载loading样式
2.新增TextScroll 组件 - 文本滚动公告
3.新增拖动demo示例，使用vue-draggable-plus库
=> refactor(index.html、demo、components、package.json): :recycle: 新增滚动公告组件、拖动demo、首屏加载样式优化

mock/menu.mock.ts, package.json, src/main.ts, src/plugins/index.ts, src/plugins/vxeTable.ts, src/styles/index.scss, src/styles/vxe-table.css, src/styles/vxe-table.scss, src/views/demo/vxe-table/index.vue
通过简单的配置实现强大的功能，适配 Element Plus 样式
如果合并的话，还需要麻烦大佬添加一个后端菜单（内容可参考PR中的Mock数据）
=> feat: :sparkles: 集成VxeTable

src/components/Upload/SingleImageUpload.vue
=> refactor(Upload): :recycle: 单图片支持点击预览
